#pragma once


#include "DX9Def.h"
#include "DX9Buffer.h"
#include "DX9Texture.h"
#include "DX9Viewport.h"
#include "DX9Matrix.h"



namespace dx9
{
	// rtypes 에 정의된 texturefiltertype 에 대응
	struct _DX9_TEXTURE_FILTER_SET
	{
		D3DTEXTUREFILTERTYPE minFilter;
		D3DTEXTUREFILTERTYPE magFilter;
		D3DTEXTUREFILTERTYPE mipFilter;
	};

	inline constexpr _DX9_TEXTURE_FILTER_SET d3dTextureFilterSets[] =
	{
		{D3DTEXF_POINT,			D3DTEXF_POINT,			D3DTEXF_NONE}		// _D3DTEXF_POINT
		, {D3DTEXF_LINEAR,		D3DTEXF_LINEAR,			D3DTEXF_NONE}		// _D3DTEXF_LINEAR
		, {D3DTEXF_LINEAR,		D3DTEXF_LINEAR,			D3DTEXF_POINT}		// _D3DTEXF_BILINEAR
		, {D3DTEXF_LINEAR,		D3DTEXF_LINEAR,			D3DTEXF_LINEAR}		// _D3DTEXF_TRILINEAR
		, {D3DTEXF_ANISOTROPIC,	D3DTEXF_ANISOTROPIC,	D3DTEXF_POINT}		// _D3DTEXF_BILINEAR_ANISO
		, {D3DTEXF_ANISOTROPIC,	D3DTEXF_ANISOTROPIC,	D3DTEXF_LINEAR}		// _D3DTEXF_TRILINEAR_ANISO
		, {D3DTEXF_ANISOTROPIC,	D3DTEXF_LINEAR,			D3DTEXF_NONE}		// _D3DTEXF_BILINEAR_ANISO_LINEAR_FOR_FONT
	};

	enum _TEXTURE_FILTER_TYPE
	{
		// Single image filters
		_D3DTEXF_POINT = 0
		, _D3DTEXF_LINEAR
		// Mipmapped image filters
		, _D3DTEXF_BILINEAR
		, _D3DTEXF_TRILINEAR
		// Mipmapped image filters with anisotropic
		, _D3DTEXF_BILINEAR_ANISO
		, _D3DTEXF_TRILINEAR_ANISO
		// min - aniso, mag - linear  for C_DX9_FONT
		, _D3DTEXF_BILINEAR_ANISO_LINEAR_FOR_FONT
		// attribute means count of filter type for ignore saving value of filter
		, _D3DTEXF_COUNT
	};

	enum _TEXTURE_ADDRESS_
	{		// texture address
		RTADDRESS_WRAP = 0
		, RTADDRESS_MIRROR
		, RTADDRESS_CLAMP
		, RTADDRESS_BORDER
		, RTADDRESS_MIRRORONCE
	};

	enum _TEXTURE_STAGE_STATE_TYPE_
	{	// stage state
		_D3DTSS_COLOROP = 0
		, _D3DTSS_COLORARG1
		, _D3DTSS_COLORARG2
		, _D3DTSS_ALPHAOP
		, _D3DTSS_ALPHAARG1
		, _D3DTSS_ALPHAARG2
		, _D3DTSS_BUMPENVMAT00
		, _D3DTSS_BUMPENVMAT01
		, _D3DTSS_BUMPENVMAT10
		, _D3DTSS_BUMPENVMAT11
		, _D3DTSS_TEXCOORDINDEX
		, _D3DTSS_BUMPENVLSCALE
		, _D3DTSS_BUMPENVLOFFSET
		, _D3DTSS_TEXTURETRANSFORMFLAGS
		, _D3DTSS_COLORARG0
		, _D3DTSS_ALPHAARG0
		, _D3DTSS_RESULTARG
		, _D3DTSS_CONSTANT
		, _D3DTSS_MAX
	};

	enum _D3D_TEXTUREOP
	{			// texture operation
		_D3DTOP_DISABLE = 0
		, _D3DTOP_SELECTARG1
		, _D3DTOP_SELECTARG2
		, _D3DTOP_MODULATE
		, _D3DTOP_MODULATE2X
		, _D3DTOP_MODULATE4X
		, _D3DTOP_ADD
		, _D3DTOP_ADDSIGNED
		, _D3DTOP_ADDSIGNED2X
		, _D3DTOP_SUBTRACT
		, _D3DTOP_ADDSMOOTH
		, _D3DTOP_BLENDDIFFUSEALPHA
		, _D3DTOP_BLENDTEXTUREALPHA
		, _D3DTOP_BLENDFACTORALPHA
		, _D3DTOP_BLENDTEXTUREALPHAPM
		, _D3DTOP_BLENDCURRENTALPHA
		, _D3DTOP_PREMODULATE
		, _D3DTOP_MODULATEALPHA_ADDCOLOR
		, _D3DTOP_MODULATECOLOR_ADDALPHA
		, _D3DTOP_MODULATEINVALPHA_ADDCOLOR
		, _D3DTOP_MODULATEINVCOLOR_ADDALPHA
		, _D3DTOP_BUMPENVMAP
		, _D3DTOP_BUMPENVMAPLUMINANCE
		, _D3DTOP_DOTPRODUCT3
		, _D3DTOP_MULTIPLYADD
		, _D3DTOP_LERP
	};

	// stage state arg type
	inline constexpr DWORD _D3DTA_DIFFUSE = D3DTA_DIFFUSE;
	inline constexpr DWORD _D3DTA_CURRENT = D3DTA_CURRENT;
	inline constexpr DWORD _D3DTA_TEXTURE = D3DTA_TEXTURE;
	inline constexpr DWORD _D3DTA_TFACTOR = D3DTA_TFACTOR;
	inline constexpr DWORD _D3DTA_SPECULAR = D3DTA_SPECULAR;
	inline constexpr DWORD _D3DTA_TEMP = D3DTA_TEMP;
	inline constexpr DWORD _D3DTA_CONSTANT = D3DTA_CONSTANT;
	inline constexpr DWORD _D3DTA_COMPLEMENT = D3DTA_COMPLEMENT;
	inline constexpr DWORD _D3DTA_ALPHAREPLICATE = D3DTA_ALPHAREPLICATE;
	inline constexpr DWORD _D3DTA_NOT_INITIALIZED = 0xffffff;

	// RS3 -> D3D 변환 테이블들
	inline constexpr D3DBLEND d3dBlendTable[] =
	{
		D3DBLEND_ZERO,
		D3DBLEND_ONE,
		D3DBLEND_SRCCOLOR,
		D3DBLEND_INVSRCCOLOR,
		D3DBLEND_DESTCOLOR,
		D3DBLEND_INVDESTCOLOR,
		D3DBLEND_SRCALPHA,
		D3DBLEND_INVSRCALPHA,
		D3DBLEND_DESTALPHA,
		D3DBLEND_INVDESTALPHA,
		D3DBLEND_SRCALPHASAT,
		D3DBLEND_BLENDFACTOR,
		D3DBLEND_INVBLENDFACTOR,
	};

	inline constexpr D3DBLENDOP d3dBlendOPTable[] =
	{
		D3DBLENDOP_ADD,
		D3DBLENDOP_SUBTRACT,
		D3DBLENDOP_REVSUBTRACT,
		D3DBLENDOP_MIN,
		D3DBLENDOP_MAX,
	};

	inline constexpr D3DCMPFUNC d3dCmpFuncTable[] =
	{
		D3DCMP_NEVER,
		D3DCMP_LESS,
		D3DCMP_EQUAL,
		D3DCMP_LESSEQUAL,
		D3DCMP_GREATER,
		D3DCMP_NOTEQUAL,
		D3DCMP_GREATEREQUAL,
		D3DCMP_ALWAYS
	};

	inline constexpr D3DPRIMITIVETYPE d3dPrimitiveTypeTable[] =
	{
		D3DPT_POINTLIST,
		D3DPT_LINELIST,
		D3DPT_LINESTRIP,
		D3DPT_TRIANGLELIST,
		D3DPT_TRIANGLESTRIP,
		D3DPT_TRIANGLEFAN,
	};

	inline constexpr D3DCULL d3dCullTable[] =
	{
		D3DCULL_NONE,
		D3DCULL_CCW,
		D3DCULL_CW,
	};

	inline constexpr D3DFILLMODE d3dFillTable[] =
	{
		D3DFILL_POINT,
		D3DFILL_WIREFRAME,
		D3DFILL_SOLID
	};

	inline constexpr D3DTEXTURESTAGESTATETYPE d3dTextureStageStateTypeTable[] =
	{
		D3DTSS_COLOROP,
		D3DTSS_COLORARG1,
		D3DTSS_COLORARG2,
		D3DTSS_ALPHAOP,
		D3DTSS_ALPHAARG1,
		D3DTSS_ALPHAARG2,
		D3DTSS_BUMPENVMAT00,
		D3DTSS_BUMPENVMAT01,
		D3DTSS_BUMPENVMAT10,
		D3DTSS_BUMPENVMAT11,
		D3DTSS_TEXCOORDINDEX,
		D3DTSS_BUMPENVLSCALE,
		D3DTSS_BUMPENVLOFFSET,
		D3DTSS_TEXTURETRANSFORMFLAGS,
		D3DTSS_COLORARG0,
		D3DTSS_ALPHAARG0,
		D3DTSS_RESULTARG,
		D3DTSS_CONSTANT,
	};

	inline constexpr D3DTEXTUREOP d3dTextureOPTable[] =
	{
		D3DTOP_DISABLE
		, D3DTOP_SELECTARG1
		, D3DTOP_SELECTARG2
		, D3DTOP_MODULATE
		, D3DTOP_MODULATE2X
		, D3DTOP_MODULATE4X
		, D3DTOP_ADD
		, D3DTOP_ADDSIGNED
		, D3DTOP_ADDSIGNED2X
		, D3DTOP_SUBTRACT
		, D3DTOP_ADDSMOOTH
		, D3DTOP_BLENDDIFFUSEALPHA
		, D3DTOP_BLENDTEXTUREALPHA
		, D3DTOP_BLENDFACTORALPHA
		, D3DTOP_BLENDTEXTUREALPHAPM
		, D3DTOP_BLENDCURRENTALPHA
		, D3DTOP_PREMODULATE
		, D3DTOP_MODULATEALPHA_ADDCOLOR
		, D3DTOP_MODULATECOLOR_ADDALPHA
		, D3DTOP_MODULATEINVALPHA_ADDCOLOR
		, D3DTOP_MODULATEINVCOLOR_ADDALPHA
		, D3DTOP_BUMPENVMAP
		, D3DTOP_BUMPENVMAPLUMINANCE
		, D3DTOP_DOTPRODUCT3
		, D3DTOP_MULTIPLYADD
		, D3DTOP_LERP
	};

	inline constexpr D3DSAMPLERSTATETYPE d3dSamplerStateTypeTable[] =
	{
		D3DSAMP_ADDRESSU,
		D3DSAMP_ADDRESSV,
		D3DSAMP_ADDRESSW,
		D3DSAMP_BORDERCOLOR,
		D3DSAMP_MAGFILTER,
		D3DSAMP_MINFILTER,
		D3DSAMP_MIPFILTER,
		D3DSAMP_MIPMAPLODBIAS,
		D3DSAMP_MAXMIPLEVEL,
		D3DSAMP_MAXANISOTROPY,
		D3DSAMP_SRGBTEXTURE,
		D3DSAMP_ELEMENTINDEX,
		D3DSAMP_DMAPOFFSET,
	};

	enum _SETTREANSFORM_TYPE
	{
		_D3DTS_WORLD = 0
		, _D3DTS_VIEW
		, _D3DTS_PROJECTION
		, _D3DTS_TEXTURE0
		, _D3DTS_TEXTURE1
		, _D3DTS_TEXTURE2
		, _D3DTS_TEXTURE3
		, _D3DTS_TEXTURE4
		, _D3DTS_TEXTURE5
		, _D3DTS_TEXTURE6
		, _D3DTS_TEXTURE7
		, _D3DTS_MAX
	};

	// depth compare function
	enum _D3D_CMP_FUNC
	{
		_D3DCMP_NEVER = 0,
		_D3DCMP_LESS,
		_D3DCMP_EQUAL,
		_D3DCMP_LESSEQUAL,
		_D3DCMP_GREATER,
		_D3DCMP_NOTEQUAL,
		_D3DCMP_GREATEREQUAL,
		_D3DCMP_ALWAYS,
		_D3DCMP_END
	};

	class C_DX9_DEVICE_STATE
	{
	protected:
		// 디렉 함수 호출 횟수를 줄이기 위해 상태를 저장해놓는다.
		_DX9_TEXTURE*			currentTextures[MAX_IMAGEUNIT]{};
		_TEXTURE_FILTER_TYPE	currentTextureFilter[MAX_IMAGEUNIT]{};
		_TEXTURE_ADDRESS_		currentTextureAddress[MAX_IMAGEUNIT][3]{};	// u,v,w
		UINT					currentTextureStageSettings[MAX_IMAGEUNIT][_D3DTSS_MAX]{};
		DWORD					currentMaxAnisotropy[MAX_IMAGEUNIT]{};
		float					currentMipmaplodBias[MAX_IMAGEUNIT]{};
		DWORD					currentTextureBorderColor[MAX_IMAGEUNIT]{};
		DWORD					currentFVF{};

		int						currentVertexFormat{};
		_DX9_VERTEX_BUFFER*		currentVertexBuffer[MAX_VERTEXSTREAM]{};
		UINT					currentVertexOffset[MAX_VERTEXSTREAM]{};
		UINT					currentFrequencyParameter[MAX_VERTEXSTREAM]{};
		_DX9_INDEX_BUFFER*		currentIndexBuffer{};
		UINT					currentInstanceCount{};	// 프로파일 보관용

		dx9::DVIEWPORT9			dx9Viewport{};

		// alpha blend
		/*
		bool					currentBlendEnable;
		RBLEND					currentSrcFactor, currentDstFactor;
		RBLENDOP				currentBlendMode;
		// SEPARATE ALPHABLEND
		bool					currentSeparateBlendEnable;
		RBLEND					currentSeparateSrcFactor, currentSeparateDstFactor;
		RBLENDOP				currentSeparateBlendMode;

		DWORD					currentBlendFactor;
		DWORD					currentTextureFactor;
		_D3D_CMP_FUNC				currentDepthFunc;
		bool					currentDepthTestEnable, currentDepthWriteEnable;
		_D3D_CMP_FUNC				currentStencilFunc, currentStencilBackFunc;
		DWORD					currentStencilRef;
		DWORD					currentStencilMask;
		bool					currentStencilEnable;
		bool					currentColorWriteEnable;
		RCULL					currentCullMode;
		RFILLMODE				currentFillMode;
		*/
		_DMATRIX9				currentTransform[_D3DTS_MAX]{};
		/*
		bool					currentLighting;
		bool					currentNormalizeNormals;
		DWORD					currentAmbientColor;
		//bool					currentAlphaBlendEnable;
		bool					currentAlphaTestEnable;
		*/
		DWORD					currentAlphaRef{};
		_D3D_CMP_FUNC			currentAlphaFunc{};
		/*
		bool					currentClipping;
		bool					currentScissorTestEnable;
		bool					currentFog;
		DWORD					currentFogColor;
		float					currentFogNear, currentFogFar;
		bool					currentVertexBlendEnable;
		bool					currentIndexedVertexBlendEnable;
		bool					currentSpecularEnable;
		*/
		DWORD dwRenderState[256]{};
		DWORD dwSamplerState[16]{};

	public:
		C_DX9_DEVICE_STATE() = default;
		virtual ~C_DX9_DEVICE_STATE() = default;

	};
}
